### ISSUE TITLE
Current stable version?

### ISSUE THREAD

**Issue by ilovezfs** [jgaeddert/liquid-dsp#112]
Based on https://github.com/jgaeddert/liquid-dsp/releases and http://liquidsdr.org I cannot tell if 1.3.0 or 1.3.1 is the current stable version.

Which version should be in Homebrew's stable spec? Thanks!

**Comment by jgaeddert** [comment]
Go with version 1.3.1. Thanks


On Thu, Oct 26, 2017, at 05:37 AM, ilovezfs wrote:
> Based on https://github.com/jgaeddert/liquid-dsp/releases and
> http://liquidsdr.org I cannot tell if 1.3.0 or 1.3.1 is the current
> stable version.> Which version should be in Homebrew's stable spec? Thanks!


> — You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub[1], or mute the
> thread[2].> 


Links:

  1. https://github.com/jgaeddert/liquid-dsp/issues/112

**Comment by ilovezfs** [comment]
Thanks @jgaeddert! https://github.com/Homebrew/homebrew-core/pull/19844 has shipped.
