### ISSUE TITLE
Install Problem on OS X 10.11.6

### ISSUE THREAD

**Issue by kavasseri** [jgaeddert/liquid-dsp#116]
Hello, 
Bootstrap fails with the following messages on OS X 10.11.6 (El Capitan)

./bootstrap.sh: line 30: aclocal: command not found
./bootstrap.sh: line 31: autoconf: command not found
./bootstrap.sh: line 32: autoheader: command not found

Thanks much!

**Comment by itdaniher** [comment]
You're missing autotools, a package installable with Homebrew on osx.

**Comment by kavasseri** [comment]
Thanks much! Its fixed now.
