### ISSUE TITLE
make 

### ISSUE THREAD

**Issue by nilampradhan2** [jgaeddert/liquid-dsp#118]
i want to install liquid-dsp, after i run ./configure i run command "make", it shows error 
make: *** No targets specified and no makefile found.  Stop.

**Comment by brian-armstrong** [comment]
That sounds like ./configure failed. Did it print out an error when you ran it?

**Comment by nilampradhan2** [comment]
no.
when i run it it display:
Script started, file is ./configure

**Comment by nilampradhan2** [comment]
i run it with commond:
sudo script ./configure
am i right?

**Comment by windytan** [comment]
You may have just inadvertently overwritten the configure file with the output of the "script" command. 

Don't run "script", just run [these](https://github.com/jgaeddert/liquid-dsp#installation):

    ./bootstrap.sh
    ./configure
    make
    sudo make install
