### ISSUE TITLE
m files are not displayed in Octave

### ISSUE THREAD

**Issue by tomwbarclay** [jgaeddert/liquid-dsp#130]
I have downloaded the latest liquid-dsp from github and built all the examples. Running modem_example and gmskmodem_example seems to be fine. They both run and I get .m files, so far so good ... 
Load Octave 4.2.2 and select a .m file and run it I get graph window(s) with no content. Has Octave changed or is the .m file output format changed ?  Any help appreciated.

**Comment by jgaeddert** [comment]
Running on Octave 4.4.0 does not provide any issues. What specific examples are you running? You might want to change your Octave GNUTERM environment. What do you get when you run the following in Octave?

    getenv('GNUTERM')

**Comment by tomwbarclay** [comment]
See below ...

>> getenv('GNUTERM')
ans =
>>

**Comment by jgaeddert** [comment]
Can you plot anything? or is it just the example outputs? What happens when you run something like

    plot(randn(1,100))

Does that produce a good plot?

**Comment by tomwbarclay** [comment]
I am sure its an Octave issue. I am running it in a VMware Ubuntu 32 bit guest OS. If I load the example  modem_example.m first then it runs OK. If I then load gmskmodem_example.m then I get 2 empty windows plotted. If I then switch back to modem_example.m, it too now produces a blank window.  Rather than waste your time I will pursue this on the Octave support sites.

**Comment by jgaeddert** [comment]
Not a waste of time at all! Just let me know if I can help in any way.

On Tue, Jun 12, 2018, at 7:17 AM, tomwbarclay wrote:
> I am sure its an Octave issue. I am running it in a VMware Ubuntu 32
> bit guest OS. If I load the example  modem_example.m first then it
> runs OK. If I then load gmskmodem_example.m then I get 2 empty windows
> plotted. If I then switch back to modem_example.m, it too now produces
> a blank window.  Rather than waste your time I will pursue this on the
> Octave support sites.> — You are receiving this because you commented. Reply to this email
> directly, view it on GitHub[1], or mute the thread[2].

Links:

  1. https://github.com/jgaeddert/liquid-dsp/issues/130#issuecomment-396554381
