### ISSUE TITLE
cannot be compiled with SSE2

### ISSUE THREAD

**Issue by bmwiedemann** [jgaeddert/liquid-dsp#137]
While working on reproducible builds for openSUSE, I found that liquid-dsp (commit 4c9a7514) cannot be compiled with SSE2

`src/dotprod/src/dotprod_cccf.mmx.c` line 49
includes and uses pmmintrin.h even when no SSE3 support is available or desired, leading to compilation errors

```
In file included from src/dotprod/src/dotprod_cccf.mmx.c:49:
/usr/lib64/gcc/x86_64-suse-linux/8/include/pmmintrin.h:50:1: error: inlining failed in call to always_inline '_mm_addsub_ps': target specific option mismatch
 _mm_addsub_ps (__m128 __X, __m128 __Y)
 ^~~~~~~~~~~~~
src/dotprod/src/dotprod_cccf.mmx.c:255:13: note: called from here
          s = _mm_addsub_ps( ci, cq );
```

**Comment by bmwiedemann** [comment]
ping. Can you reproduce this? Anything else I can help?

**Comment by fsheikh** [comment]
Yeah I could also see this with a [force](bda85df80e9b860217e6f7cf55c1e969b9749084) compilation for SSE2 on x86/Ubunut 16.04. Fix patch underway
