### ISSUE TITLE
Possible NULL pointer dereference

### ISSUE THREAD

**Issue by ashley-b** [jgaeddert/liquid-dsp#166]
The check for _q == NULL is done after _q->M

https://github.com/jgaeddert/liquid-dsp/blob/b1f8da417960198af87b244337f0dc06a2df65db/src/modem/src/modem_common.c#L370-L376

**Comment by jgaeddert** [comment]
Good catch. I meant to check that _q->symbol_map wasn't NULL, not the main object.

Fixed in be24d2b821426faa942155e360cea44b34a73297
