### ISSUE TITLE
Version 1.3.1 very old

### ISSUE THREAD

**Issue by dl1chb** [jgaeddert/liquid-dsp#170]
The Version is very old (Oct 24, 2017). Therefore 1.3.1 is the newest version in the linux distros. With this version, the examples won't build. I just built the newest version for fedora and everything works.

So please release a new version having a version number ;-)

**Comment by jgaeddert** [comment]
v1.3.2 released! Thanks for poking me on this.

**Comment by dl1chb** [comment]
Just for a comment for Fedora Distributors: there where some unecessary patches which are no longer requiered. For the Specfile, see: https://github.com/dl1chb/rf-tools/blob/master/liquid-dsp.spec
