### ISSUE TITLE
Add Repology badge to README.md

### ISSUE THREAD

**Issue by luzpaz** [jgaeddert/liquid-dsp#172]
### Summary
A way for users to see what downstream repositories carry liquid-dsp

### Proposed design
The full badge looks like so:  
[![Packaging status](https://repology.org/badge/vertical-allrepos/liquid-dsp.svg?header=liquid-dsp)](https://repology.org/project/liquid-dsp/versions)  

but since it take up a lot of room it can be simply added as a single badge such as:

[![Packaging status](https://repology.org/badge/tiny-repos/liquid-dsp.svg)](https://repology.org/project/liquid-dsp/versions)

**Comment by jgaeddert** [comment]
That's pretty slick. Thanks! Added to the README.
