### ISSUE TITLE
FSK Framesync doesn't reset state after invalid header

### ISSUE THREAD

**Issue by alog243** [jgaeddert/liquid-dsp#176]
Self-explanatory title.

fskframesync.c line 577 doesn't have a `fskframesync_reset(_q);` like other framing schemes.
This means if you ever receive an invalid header the framesync state is stuck until it corrupts the heap and crashes because of line 521:

> `_q->header_sym[_q->symbol_counter++] = sym;`

The only check against the symbol counter is an == check, instead of a >= check (and it happens after you write the heap so that doesn't stop it from corrupting anyway).

There's no way to actually recover from this state without the framesync reset.

**Comment by jgaeddert** [comment]
Should be resolved with 744fb4d60fac4771a4cc32946023d1305f13a219. Please verify.

**Comment by alog243** [comment]
Yup, it works now. I didn't look at all of the other framesync objects so I don't know if the reset is missing anywhere else; I was just working with the FSK frames when I noticed it.

**Comment by jgaeddert** [comment]
It's a fair point. This is one of those areas that having more unit tests (e.g. `make check`) for these frame synchronizers would be useful.

**Comment by jgaeddert** [comment]
(btw, thanks!)
