### ISSUE TITLE
MATLAB Plotting Not Working in resamp_crcf_example.c

### ISSUE THREAD

**Issue by AGS-Nelson** [jgaeddert/liquid-dsp#201]
Seemingly simple issue, the syntax used for plotting is not working and gives errors in R2019a MATLAB.  
Examples:
```
Error using plot
Invalid data argument.

Error in resamp_crcf_example (line 887)
  plot(tx,real(x),'-s','Color',[0.5 0.5 0.5],'MarkerSize',1,...
```

```
Error using plot
Invalid data argument.

Error in resamp_crcf_example (line 894)
  plot(tx,imag(x),'-s','Color',[0.5 0.5 0.5],'MarkerSize',1,...
```

```
Error using plot
Vectors must be the same length.

Error in resamp_crcf_example (line 913)
  plot(fx,X,'Color',[0.5 0.5 0.5],fy,Y,'LineWidth',2);
```
I just removed the extra plotting flags and added a '-o' option to the resampler output to make it look decent, not sure if there are issues in other examples too.
![resampler_0 6](https://user-images.githubusercontent.com/52461563/83032550-fee52e80-a003-11ea-9340-2bcd39d07845.png)

**Comment by jgaeddert** [comment]
Yes, my apologies. I don't really use MATLAB, but rather [octave](https://www.gnu.org/software/octave/) which has a few differences in plotting commands.

**Comment by AGS-Nelson** [comment]
Ah ok, I was wondering if that was the case.  I will keep that in mind, should be possible to have the commands work the same in MATLAB and Octave with some tweaks.
