### ISSUE TITLE
how can I get the phase error between a real signal and nco output? 

### ISSUE THREAD

**Issue by hzsch** [jgaeddert/liquid-dsp#206]
The lib of pll part only has complex signal , but I have to use the real signal. Can I get some help?

**Comment by hzsch** [comment]
I already try some methods,but can not get the correct result.
![image](https://user-images.githubusercontent.com/23236381/85375367-ca17b900-b568-11ea-8049-4ea97645d646.png)

**Comment by jgaeddert** [comment]
If the input signal is real-valued, you can just re-define what the phase error looks like. Here's a stand-alone example:

```C
// pll_real_example.c : simulation of a real-valued phase-locked loop

#include <stdio.h>
#include <stdlib.h>
#include <math.h>

int main() {
    // parameters and simulation options
    float        phase_in     =  3.00f;     // carrier phase offset
    float        frequency_in =  0.40;      // carrier frequency offset
    float        alpha        =  0.002f;    // PLL bandwidth
    unsigned int n            =   400;      // number of samples

    // initialize states
    float beta          = sqrtf(alpha);     // phase adjustment factor
    float phase_out     = 0.0f;             // output signal phase
    float frequency_out = 0.45f;            // output signal frequency

    // print line legend to standard output
    printf("# %6s %12s %12s %12s %12s %12s\n",
            "index", "input", "output", "phase error", "filtered", "freq. error");

    // run basic simulation
    unsigned int i;
    for (i=0; i<n; i++) {
        // compute input and output signals
        float signal_in  = sinf(phase_in);
        float signal_out = sinf(phase_out);

        // compute phase error estimate
        float error_signal = signal_in * cosf( phase_out );

        // apply loop filter and correct output phase and frequency
        frequency_out += alpha * error_signal;    // adjust phase
        phase_out     +=  beta * error_signal;    // adjust frequency

        // plotting: phase error (modulo pi)
        float phase_error = phase_in - phase_out;
        while (phase_error >  M_PI) phase_error -= M_PI;
        while (phase_error < -M_PI) phase_error += M_PI;

        // plotting: frequency error
        float freq_error = frequency_in - frequency_out;

        // print results to standard output for plotting
        printf("  %6u %12.8f %12.8f %12.8f %12.8f %12.8f\n",
                  i, signal_in, signal_out, error_signal, phase_error, freq_error);

        // increment input and output phase values
        phase_in  += frequency_in;
        phase_out += frequency_out;
    }
    return 0;
}
```

**Comment by hzsch** [comment]
Thank you very much for your answer. It helped me a lot and solved the problem that&nbsp;bothered me for a long time.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Joseph D. Gaeddert"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月27日(星期六) 晚上10:48
收件人:&nbsp;"jgaeddert/liquid-dsp"<liquid-dsp@noreply.github.com&gt;;
抄送:&nbsp;"宋超"<songchao2012@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [jgaeddert/liquid-dsp] how can I get the phase error between a real signal and nco output?  (#206)





 
If the input signal is real-valued, you can just re-define what the phase error looks like. Here's a stand-alone example:
 // pll_real_example.c : simulation of a real-valued phase-locked loop #include <stdio.h&gt; #include <stdlib.h&gt; #include <math.h&gt; int main() {     // parameters and simulation options     float        phase_in     =  3.00f;     // carrier phase offset     float        frequency_in =  0.40;      // carrier frequency offset     float        alpha        =  0.002f;    // PLL bandwidth     unsigned int n            =   400;      // number of samples     // initialize states     float beta          = sqrtf(alpha);     // phase adjustment factor     float phase_out     = 0.0f;             // output signal phase     float frequency_out = 0.45f;            // output signal frequency     // print line legend to standard output     printf("# %6s %12s %12s %12s %12s %12s\n",             "index", "input", "output", "phase error", "filtered", "freq. error");     // run basic simulation     unsigned int i;     for (i=0; i<n; i++) {         // compute input and output signals         float signal_in  = sinf(phase_in);         float signal_out = sinf(phase_out);         // compute phase error estimate         float error_signal = signal_in * cosf( phase_out );         // apply loop filter and correct output phase and frequency         frequency_out += alpha * error_signal;    // adjust phase         phase_out     +=  beta * error_signal;    // adjust frequency         // plotting: phase error (modulo pi)         float phase_error = phase_in - phase_out;         while (phase_error &gt;  M_PI) phase_error -= M_PI;         while (phase_error < -M_PI) phase_error += M_PI;         // plotting: frequency error         float freq_error = frequency_in - frequency_out;         // print results to standard output for plotting         printf("  %6u %12.8f %12.8f %12.8f %12.8f %12.8f\n",                   i, signal_in, signal_out, error_signal, phase_error, freq_error);         // increment input and output phase values         phase_in  += frequency_in;         phase_out += frequency_out;     }     return 0; }
