### ISSUE TITLE
./configure --prefix=     not possible?

### ISSUE THREAD

**Issue by jrmims** [jgaeddert/liquid-dsp#224]
I'm trying to build liquid dsp in specific directories using` --prefix=<path to directory>`. I'm getting the error ```make: *** No rule to make target `src/libliquid.o', needed by `libliquid.a'.  Stop.``` when I run `make` in that directory.

**Comment by jgaeddert** [comment]
What OS is this on?

**Comment by jgaeddert** [comment]
I wasn't able to reproduce this on a Debian build. The `--prefix` option with `configure` should only affect the install directory. Can you try doing a full build from scratch? That is `make distclean` and then re-run `./bootstrap.sh && ./configure --prefix=/path/to/install/directory && make`?

**Comment by jrmims** [comment]
Thanks for getting back to me! I believe the issue was I was running configure from inside the install directory with `../configure --prefix=/path && make`

Running everything from inside the base liquiddsp directory worked perfectly!
