### ISSUE TITLE
Question regarding flexframegen

### ISSUE THREAD

**Issue by mryndzionek** [jgaeddert/liquid-dsp#225]
I'm trying to use the `flexframegen` object with different modulation schemes. When I look at a IQ waterfall the signals look very similar regardless of the modulation scheme used (same, constant payload):
BPSK
![bpsk_](https://user-images.githubusercontent.com/786191/111042667-cdc4d600-843e-11eb-956e-da5cc9c782e3.png)

QPSK
![qpsk_](https://user-images.githubusercontent.com/786191/111042671-d1585d00-843e-11eb-8bfe-dd1fc2d4aa55.png)

ASK2
![ask2_](https://user-images.githubusercontent.com/786191/111042672-d3222080-843e-11eb-952d-6e5c0260703b.png)

Is this supposed to be this way? BPSK and ASK2 look almost the same...

**Comment by pfeatherstone** [comment]
BPSK and ASK2 are the same

**Comment by pfeatherstone** [comment]
Somewhere in the liquid docs there will be some pictures of the different constellations. There you will see BPSK is the same as ASK2, QPSK is the same as PSK4 (maybe there is a phase difference of pi/4,  it sure)

**Comment by mryndzionek** [comment]
Okay, I've found it: https://liquidsdr.org/doc/modem/
