### ISSUE TITLE
Unable to find x86_64 fec Shared Package

### ISSUE THREAD

**Issue by Revathy0427** [jgaeddert/liquid-dsp#226]
@michelp @guruofquality @jgaeddert 
Hello, I cloned the liquid-dsp repo and installed it. Then I tried to install Redhawk components into the TARGET SDR .  But when I tried installing the components I am getting this error.

**checking for fec_v3... no
configure: error: "Unable to find x86_64 fec Shared Package"**

Here is the link to the REDHAWK IDE components I tried to install: https://github.com/lmcadoo2/RedhawkComponents

What should I do to overcome this? Kindly help. Thank you.

**Comment by jgaeddert** [comment]
Looks as though there is a separate fork of liquid that they want installed. From the README in your link:

> PLEASE NOTE: Some versions of liquid downloaded will not compile with these components. For best results, use lmcadoo2/liquid-dsp

I'm guessing that there's a separate FEC (forward error-correction) library that they want used for this.
