### ISSUE TITLE
Question: waterfall

### ISSUE THREAD

**Issue by pfeatherstone** [jgaeddert/liquid-dsp#227]
@jgaeddert How did you generate the figure [fig-asgram-example-waterfall] in https://liquidsdr.org/doc/asgram? Does liquid provide functionality for writing a high resolution waterfall plot?

**Comment by jgaeddert** [comment]
Yes! There is an `spwaterfallcf` object that computes the spectrum plot; however I don't seem to have documentation on it at the moment.

**Comment by pfeatherstone** [comment]
i'm happy generating spectrogram traces given an FFT size and a number of FFT averages per trace, but i'm not entirely sure how to convert a trace of floating point numbers to pixel values.
