### ISSUE TITLE
Question : FSK - what are "good" parameters.

### ISSUE THREAD

**Issue by pfeatherstone** [jgaeddert/liquid-dsp#231]
I've been playing with ```fskmodem_example.c``` in the examples folder.
I'm trying to understand how ```fskmod``` works.
So we have:
* ```m``` : bits per symbol
* ```k```: number of samples per symbol, typically equal to ```2^m``` but a good value is ```2^(m+1)```
* ```bw```: the cutoff frequency

So there are ```M = 2^m``` possible symbols in range ```0 <= s <= 2^m - 1```.
Each symbol occupies a slice of the bandwidth. So symbol ```s``` has normalized frequency ```f_s = (s - M2) * bw / M2```
where:
* ```M2 = (M-1)/2```
So symbol ```s=0``` has normalized frequency ```f = -bw``` and symbol ```s=M-1``` has normalized frequency ```f = +bw```.

Now it looks like each symbol ```s``` gets modulated by generating a tone of ```k``` samples at its normalized frequency, i.e
```f = (s - M2) * bw / M2```

What I don't understand is how ```k``` and ```bw``` affect the shape of the signal.

So if I use:
* ```m = 3;```
* ```k = 2 << m;``` (=16) (recommended value from the example)
* ```bw = 0.2``` (recommended value form the example)

I get the following signal:
![fsk_3_16_0 2](https://user-images.githubusercontent.com/45853521/119361173-46e47300-bca3-11eb-9d22-45465dc5f063.png)

If I use:
* ```m = 3;```
* ```k = 32;```
* ```bw = 0.2```

I get the following:
![fsk_3_32_0 2](https://user-images.githubusercontent.com/45853521/119361408-8a3ee180-bca3-11eb-9e53-222a305511e1.png)

Now if I play with bandwidth:

* ```m=3;```
* ```k=16;``` (recommended)
* ```bw=0.1;```

I get:
![fsk_3_16_0 1](https://user-images.githubusercontent.com/45853521/119361665-d38f3100-bca3-11eb-8bff-dadc4cb292f6.png)

* ```m=3;```
* ```k=32;```
* ```bw=0.1;```

I get:
![fsk_3_32_0 1](https://user-images.githubusercontent.com/45853521/119361865-05a09300-bca4-11eb-81ce-2ca412e33c76.png)

* ```m=3;```
* ```k=64;```
* ```bw=0.1;```

I get:

![fsk_3_64_0 1](https://user-images.githubusercontent.com/45853521/119361981-2537bb80-bca4-11eb-94c2-a36abcf3f2f4.png)

So it looks like ```k``` is affecting the rolloff. Is that right?

What is causing the rippling?

How do I judge what a good value for ```k``` is given ```m``` and ```bw```?

@jgaeddert Thank you

**Comment by pfeatherstone** [comment]
Ah, is the rippling on top basically the ```2 ^ 3 = 8``` (for ```m=3```) tones starting to appear?

**Comment by pfeatherstone** [comment]
Is there a way to guarantee a flat top?

**Comment by pfeatherstone** [comment]
@jgaeddert @brian-armstrong any ideas?

**Comment by jgaeddert** [comment]
It's a tradeoff between error rate and bandwidth. Minimum spacing (which I think gives a flat top) is where the carrier spacing is equal to the symbol rate.

**Comment by pfeatherstone** [comment]
So carrier spacing is ```bw / M = bw / (2^m)``` and symbol rate is ```bw/k```.
So we want ```k = 2^m``` ?

**Comment by pfeatherstone** [comment]
So bandwidth is ```2*bw``` using your variable names (in the code you use ```bw``` for a cutoff frequency i think, hence the factor of 2)
So carrier spacing is ```2*bw / (2^m - 1)``` and symbol rate is ```1/k```.
So we want ```k = (2^m - 1) / (2*bw)```
So if ```bw = 0.25``` and bandwidth is 0.5 then ```k = 2 * (2 ^m - 1) = 2^(m+1) - 2```.
so we are close to the default value used in the example which is ```k = 2 << m = 2^(m+1)```

Is this right?

**Comment by pfeatherstone** [comment]
Hmm doesn't give me a flat top.
I used ```m=3```, ```fc = 0.2```, then ``` k = (2^m - 1) / (2*fc) = 17.5 ~ 18```
Which gives me:
![fsk_3_18_0 2](https://user-images.githubusercontent.com/45853521/119514306-cee27f80-bd6c-11eb-9200-aae395b792c3.png)

**Comment by jgaeddert** [comment]
I need to double check the values. Those spikes are probably a result of not maintaining phase continuity between symbols.

**Comment by jgaeddert** [comment]
More precisely, each like symbol is within phase.

**Comment by pfeatherstone** [comment]
> I need to double check the values. Those spikes are probably a result of not maintaining phase continuity between symbols.

Does liquid not maintain phase continuity in fskmodem ?

**Comment by jgaeddert** [comment]
So liquid absolutely maintains phase continuity between adjacent symbols. I think I mis-"spoke" with my previous comment. If all like symbols have the same phase then you'll see spikes in the spectral estimate. It all depends upon the parameters of the FSK modulator you've supplied.
