### ISSUE TITLE
Question : build subset of modules

### ISSUE THREAD

**Issue by pfeatherstone** [jgaeddert/liquid-dsp#237]
Looking at the configure script, you have options:
```--disable-FEATURE``` and ```--enable-FEATURE```

Is there a way to list the features?
Is there a way to disable all of them and then re-enable a subset of them?
For example, how do i build the forward error correction feature only?

**Comment by jgaeddert** [comment]
I think you can run `./configure --help` for options but this won't build subsets of the modules. Some of them (such as FEC) don't have other internal dependencies but many of them do. For example, framing depends on dotprod, filter, fec, fft, modem, math, multicarrier and a few others.
