### ISSUE TITLE
Typo in write up for Phase-Locked Loop tutorial

### ISSUE THREAD

**Issue by harrylippy** [jgaeddert/liquid-dsp#242]
In the final paragraph, there is text that reads:

_Notice also that the difference in phase of the last several samples (i.e. the difference between the phase at steps 38 and 39 ) is approximately 0.1 which is the initial frequency offset that was given in the beginning._ 

0.1 should be 0.01

**Comment by jgaeddert** [comment]
Good catch! Fixed.
