### ISSUE TITLE
Complex notch filter

### ISSUE THREAD

**Issue by pfeatherstone** [jgaeddert/liquid-dsp#250]
Currently ```liquid_firdes_notch()``` creates a real-only filter. So, say you want to drown out frequency ```fc```, you're also doing it for ```-fc```. Example:
```
    const int m = 50;
    const float fc = 0.4;
    vector<float> h_r(2*m+1);
    liquid_firdes_notch(m, fc, 60, &h_r[0]);
```
gives you the following frequency response:
![notch_real](https://user-images.githubusercontent.com/45853521/130025557-f00cc476-4998-4c9e-ba4f-e99ec11ddd11.png)

So I looked at the code, and adapted it for both real and complex filters:
```
    template <typename T>
    struct remove_complex {typedef T type;};
    template <typename T>
    struct remove_complex<std::complex<T> > {typedef T type;};
    template<typename T>
    using remove_complex_t = typename remove_complex<T>::type;

template<typename R>
R kaiser_function(
    size_t i,
    size_t wlen,
    R      beta
)
{
    static_assert(std::is_floating_point<R>::value, "template parameter should be a floating point type");
    if (i >= wlen)
        throw std::runtime_error("i < wlen not satisfied");
    if (beta <= 0)
        throw std::runtime_error("beta should be strictly positive");

    const R t = (R)i - (R)(wlen-1)/2;
    const R r = 2.0*t/(R)(wlen-1);
    const R a = boost::math::cyl_bessel_i(0, beta*sqrt(1-r*r));
    const R b = boost::math::cyl_bessel_i(0, beta);
    return a / b;
}

/*
 * Use template function overloading. 
 * This is a bit less messy than using loads of type traits 
 * to resolve the cases where you want to return complex tone or real tone.
 */
template<typename T>
void tone_(T phase, T& v)
{
    v = std::cos(phase);
}

template<typename T>
void tone_(T phase, std::complex<T>& v)
{
    v = std::polar<T>(T(1), phase);
}

template<typename T>
std::vector<T> notch_filter(size_t m, float fc)
{
    using R = remove_complex_t<T>;
    static_assert(std::is_floating_point<R>::value, "template parameter should be a floating point or complex floating point type");
    
    if (fc < -0.5 || fc > +0.5)
        throw std::runtime_error("fc must be in range (-0.5,+0.5)");
    
    std::vector<T> h(2*m+1);
    R scale = 0;
    
    for (size_t i = 0 ; i < h.size() ; i++)
    {
        const R w     = kaiser_function<R>(i, h.size(), 10.0);
        const R phase = 2*M_PI*fc*i;
        tone_(phase, h[i]);
        scale += std::norm(h[i])*w;
        h[i] *= -w;
    }
    
    for (size_t i = 0 ; i < h.size() ; i++)
        h[i] /= scale;
    
    h[m] += R(1);
    
    return h;
}
```

Now i can create a complex valued filter like so:
```
auto h = notch_filter<complex<float>>(50, 0.4);
```

And i get frequency response:
![notch_complex](https://user-images.githubusercontent.com/45853521/130026507-7be01d22-7c25-43ad-9b7a-80814fbff821.png)

IS THIS  A CORRECT FILTER??

It would seem you get the desired behavior but you get funny behavior when ```m``` gets too large. 
So here is the progression:
```
auto h1 = notch_filter<complex<float>>(100, 0.4);
auto h2 = notch_filter<complex<float>>(110, 0.4);
auto h3 = notch_filter<complex<float>>(120, 0.4);
auto h4 = notch_filter<complex<float>>(125, 0.4);
auto h5 = notch_filter<complex<float>>(126, 0.4);
auto h6 = notch_filter<complex<float>>(127, 0.4);
auto h7 = notch_filter<complex<float>>(128, 0.4);
```
These have the following frequency responses:
![notch_complex_100](https://user-images.githubusercontent.com/45853521/130038145-ec291c91-4ce4-4af0-a99e-6858bd7e860a.png)
![notch_complex_110](https://user-images.githubusercontent.com/45853521/130038158-5dd1f96a-951b-4365-b461-e9d70386c6f0.png)
![notch_complex_120](https://user-images.githubusercontent.com/45853521/130038178-a2167060-5707-47e8-92e9-3cc8b4ccbaf7.png)
![notch_complex_125](https://user-images.githubusercontent.com/45853521/130038197-a3bcb3a0-84a1-4b7b-9b77-e1baae76f3cf.png)
![notch_complex_126](https://user-images.githubusercontent.com/45853521/130038208-92947317-fa7e-4edb-88ce-44762b4e01e3.png)
![notch_complex_127](https://user-images.githubusercontent.com/45853521/130038217-f67e3b9f-6219-407d-9a0e-e0060469648d.png)
![notch_complex_128](https://user-images.githubusercontent.com/45853521/130038226-31d6e940-8e5f-4343-8639-024378a676ed.png)

ANYBODY KNOW WHAT'S GOING ON HERE?

Note that using ```complex<double>``` instead of ```complex<float>``` doesn't solve it. So it doesn't seem to be a floating point precision problem...

**Comment by pfeatherstone** [comment]
OK found the bug:
```
const R phase = 2*M_PI*fc*i;
```
->
```
const R phase = 2*M_PI*fc*(R(i) - R(m));
```

Then everything works as expected.

**Comment by pfeatherstone** [comment]
So working code is:
```
template <typename T>
struct remove_complex {typedef T type;};
template <typename T>
struct remove_complex<std::complex<T> > {typedef T type;};
template<typename T>
using remove_complex_t = typename remove_complex<T>::type;

template<typename R>
R kaiser_function(
    size_t i,
    size_t wlen,
    R      beta
)
{
    static_assert(std::is_floating_point<R>::value, "template parameter should be a floating point type");
    if (i >= wlen)
        throw std::runtime_error("i < wlen not satisfied");
    if (beta <= 0)
        throw std::runtime_error("beta should be strictly positive");

    const R t = (R)i - (R)(wlen-1)/2;
    const R r = 2.0*t/(R)(wlen-1);
    const R a = boost::math::cyl_bessel_i(0, beta*sqrt(1-r*r));
    const R b = boost::math::cyl_bessel_i(0, beta);
    return a / b;
}

/*
 * Use template function overloading. 
 * This is a bit less messy than using loads of type traits 
 * to resolve the cases where you want to return complex tone or real tone.
 */
template<typename T>
void tone_(T phase, T& v)
{
    v = std::cos(phase);
}

template<typename T>
void tone_(T phase, std::complex<T>& v)
{
    v = std::polar<T>(T(1), phase);
}

template<typename T>
std::vector<T> notch_filter(size_t m, float fc)
{
    using R = remove_complex_t<T>;
    static_assert(std::is_floating_point<R>::value, "template parameter should be a floating point or complex floating point type");
    
    if (fc < -0.5 || fc > +0.5)
        throw std::runtime_error("fc must be in range (-0.5,+0.5)");
    
    std::vector<T> h(2*m+1);
    R scale = 0;
    
    for (size_t i = 0 ; i < h.size() ; i++)
    {
        const R w     = kaiser_function<R>(i, h.size(), 10.0);
        const R phase = 2*M_PI*fc*(R(i) - R(m));
        tone_(phase, h[i]);
        scale += std::norm(h[i])*w;
        h[i] *= -w;
    }
    
    for (size_t i = 0 ; i < h.size() ; i++)
        h[i] /= scale;
    
    h[m] += R(1);
    
    return h;
}
```

**Comment by pfeatherstone** [comment]
To give some context: i want to drown out a frequency bin of some signal. Say i have some IQ, I want to zero a 1 of 512 frequency bins for examples. I thought of two ways of doing it:
* convolve with a notch filter and figure out the filter length in order to get the appropriate frequency resolution, i.e. 1/512
* use a polyphase filter bank, using 512 subfilter length, then zero the target frequency bin, then do the reverse transformation.

Anybody have an opinion on which is best? Also, are they mathematically equivalent?

**Comment by jgaeddert** [comment]
liquid does support a notch filter off DC: https://github.com/jgaeddert/liquid-dsp/blob/master/include/liquid.h#L2610-L2616

The `firfilt_cccf_notch_example.c` demonstrates this:

<img width="796" alt="image" src="https://user-images.githubusercontent.com/253027/130331509-86a61815-289e-46c1-b702-869e2c356dc8.png">

This is the difference between `firfilt_crcf` and `firfilt_cccf`; with real coefficients, the response is always symmetric so a notch at e.g. 0.2 Fs also appears at -0.2 Fs. But with complex coefficients, the notch can be at any specific frequency (and _only_ that frequency) you want.

**Comment by jgaeddert** [comment]
As for your question about whether or not a notch filter or channelizer is best, they certainly are not equivalent, but depending upon what you're doing they might give you similar results. Here's a quick run-down of the difference:

  * channelizer approach (e.g .`firpfbch2` analysis followed by `firpfbch2` synthesis) will give you good resolution and the ability to notch frequencies arbitrarily.
  * channelizer will allow you to adjust gains on sub-channels as well, if you would need it
  * the notch filter probably requires a lot less computation
  * the notch filter can operate one sample at a time (one sample in, one sample out); the channelizer would need to work on blocks of samples (e.g. 256 in, 256 out)
  * they would have comparable processing delays (e.g. impulse in would see about the same number of samples delay before appearing on the output)
  * the channelizer would have a small (probably negligible) amount of distortion in the pass-band. It's not a true perfect reconstruction filter, although it's very very close

**Comment by pfeatherstone** [comment]
Cheers @jgaeddert for the explanations and pointing out the existing code. Looking at it, you create a DC blocker then mix appropriately. That's equivalent to what I posted the second time round so all good there.

**Comment by pfeatherstone** [comment]
I think the channelizer approach is more flexible anyway. You can zero out the exact frequency bins. Using the notch filter, it isn't obvious to me how you choose the filter length to zero out a specified frequency range.

**Comment by pfeatherstone** [comment]
I'm sorry, this isn't an issue, more of a discussion.

**Comment by jgaeddert** [comment]
No apology necessary! Nice discussion.
