### ISSUE TITLE
maximum float value?

### ISSUE THREAD

**Issue by dj0abr** [jgaeddert/liquid-dsp#254]
just a question:

is there any limitation on the maximum value for the DSP routines?
i.e.: should the float values be within -1 .. +1, or can it be any value.
Is there any risk of "clipping" if values like -10 .. +10 are used ?

Thanks
Kurt

**Comment by jgaeddert** [comment]
In general, the answer is no.

Most of liquid uses single-precision floating-point math which doesn't have practical limitations for value. That being said, `float` values do have limits, and putting excessively large values in might reduce precision (e.g. trying to add `1e6f` to `1e-6f` will probably result in just `1e6f`). This isn't an issue for most applications, though.

There is also a branch to run in fixed-point math. This certainly does have practical limitations with clipping. This branch isn't up to date, though.

**Comment by dj0abr** [comment]
thank you
