### ISSUE TITLE
Internal version bump

### ISSUE THREAD

**Issue by cjcliffe** [jgaeddert/liquid-dsp#26]
If you could bump the 1.2.x version on feature commits it'd be helpful during compilation so that it can detect whether things new things like FSK modem are available and provide an out-of-date warning.

Thanks!

**Comment by jgaeddert** [comment]
I'll bump the version as soon as all the modules are tested. Should be pretty soon.

**Comment by jgaeddert** [comment]
v1.3.0 tagged
