### ISSUE TITLE
build fail: isnan not defined for complex numbers

### ISSUE THREAD

**Issue by viraptor** [jgaeddert/liquid-dsp#34]
With gcc 5.3.0, I get:

```
In file included from src/math/src/polyc.c:43:0:
src/math/src/poly.findroots.c: In function ‘polyc_findroots_bairstow_recursion’:
src/math/src/poly.findroots.c:305:9: error: non-floating-point argument in call to function ‘__builtin_isnan’
         if (isnan(du) || isnan(dv)) {
         ^
```

isnan doesn't work for T == `double complex` (works fine in clang though)

This applies to current master (f6a33a6)

**Comment by jgaeddert** [comment]
Interesting. Let me see if I can find a way to work around the isnan check.

**Comment by jgaeddert** [comment]
I pushed 3055eb3da9 which might fix this. Could you please confirm?

**Comment by viraptor** [comment]
That fixed it, thanks!
