### ISSUE TITLE
Tiny typo in documentation for half-band filter

### ISSUE THREAD

**Issue by tomneda** [jgaeddert/liquid-dsp#346]
Hello Joseph,
great using your Liquid-DSP. Thanks for that.

I found a small typo: I tried out the example in [https://liquidsdr.org/doc/resamp2/](https://liquidsdr.org/doc/resamp2/) and it was not working as the
line with `float As=-60.0f; `
should be `float As=60.0f; ` (only positive values are allowed).

In the example files it is correct.

BR
Thomas

**Comment by luzpaz** [comment]
cc @jgaeddert

**Comment by jgaeddert** [comment]
Good catch, and thanks! I've made the fix.
