### ISSUE TITLE
liquid-dsp pypi build instructions

### ISSUE THREAD

**Issue by justingray** [jgaeddert/liquid-dsp#386]
Hello,

I was trying to build your python to C++ binding as described here https://pypi.org/project/liquid-dsp/ but I was unable to find any of the necessary pybind wrappers or other necessary files to do a `pip install .` Perhaps I'm just missing some nuance, my eventual goal is to flesh out some of the bindings for symtrack.

Thank you

**Comment by seonlee2013** [comment]
好啊，邮件收到啦！
Hi, your email is arrived safely

**Comment by justingray** [comment]
I realized I probably need to be on `bind-scikit-build-dev` still having issues building, but that could be a personal problem.

**Comment by justingray** [comment]
the build instruction was `pip install .` I only had success running `python -m build` to generate my own whl file
