### ISSUE TITLE
./bootstrap.sh no such file....

### ISSUE THREAD

**Issue by yo2ldk** [jgaeddert/liquid-dsp#57]
I cannot install because of this; aclocal,autoconf,autoheader not found...
 clone was good make it
  what can I do?

**Comment by jgaeddert** [comment]
You need to install autotools for this to work. Depending on your Linux distro this can be as simple as

    sudo apt-get install automake autoconf

**Comment by jarodcs** [comment]
Thanks, this was helpful!

**Comment by lobocv** [comment]
@jgaeddert Could I suggest you add this as requirement in the README? I had this problem too and I'm sure many others will.

**Comment by jgaeddert** [comment]
Sure thing!

**Comment by jgaeddert** [comment]
Done. 33503b4cad3f13103486076cc268b3b2889a4357

**Comment by lobocv** [comment]
Thanks! Great work on the library by the way. I'm excited to get to use it and hopefully think of something to contribute!
