### ISSUE TITLE
discussion about using liquid-dsp for BTLE packet capturing in Raspberry Pi 3

### ISSUE THREAD

**Issue by chakpongchung** [jgaeddert/liquid-dsp#74]
https://github.com/drtyhlpr/ble_dump

I have tried this on Raspberry Pi 3. The processing speed does not seem fast enough to capture a packet since it keeps emitting "OOOOOO" message. Similarly I tried FM radio receiver on Raspberry Pi 3 and it had similar problems.

Is it doable of implementing a BLE, WIFI, GSM, LTE scanner using liquid-dsp to be deployed in Raspberry Pi 3? At this stage I am mainly interested in BLE. The output should be able to be displayed using wireshark.

The output of  the above repository on ubuntu is good enough at this stage.

**Comment by jgaeddert** [comment]
I'm sorry. I cannot really comment on the implementation in the link provided. The RPi3 should be plenty fast for FM radio, GSM, and certain bandwidths of LTE, though. WiFi is a bit of stretch, though. Not sure about BLE.
