### ISSUE TITLE
Use sse3 should be optionally enabled when supported by the system

### ISSUE THREAD

**Issue by athoik** [jgaeddert/liquid-dsp#83]
Hi, 

Since https://github.com/jgaeddert/liquid-dsp/commit/b3ed2ffb974fa0d3ac7fe4dae214e5855911234a crosscompiling using OpenEmbedded fails. 

```
| mipsel-oe-linux-gcc  -mel -mabi=32 -mhard-float -march=mips32 --sysroot=....  -Os -pipe -g -feliminate-unused-debug-types -I . -I include -Wall -fPIC -msse3 -Os -pipe -g -feliminate-unused-debug-types     -c -o src/audio/src/cvsd.o src/audio/src/cvsd.c
| mipsel-oe-linux-gcc: error: unrecognized command line option '-msse3'
```

Is it possible to add a proper test in order to enable sse3 instead of hardcoding to CFLAGS?

E.g.  http://www.gnu.org/software/autoconf-archive/ax_ext.html

**Comment by brian-armstrong** [comment]
Hi @athoik ,

Try this patch https://github.com/jgaeddert/liquid-dsp/pull/82

The SSE flags were being added automatically, but the hardcoded flag was then also added due to a mixup, I believe
