### ISSUE TITLE
kaiser function parameters in documentation don't match prototype.

### ISSUE THREAD

**Issue by hansvi** [jgaeddert/liquid-dsp#87]
in http://liquidsdr.org/doc/windowing/ kaiser is defined as  kaiser(n,N,dt,beta), but in liquid.h it is defined as:
float kaiser(unsigned int _n,
             unsigned int _N,
             float        _beta,
             float        _dt);

The dt and beta parameters are reversed.

**Comment by jgaeddert** [comment]
Good catch. I'm actually in the process of auto-generating the API from the source to ensure the documentation matches. Not sure when I'll roll it out.

**Comment by jgaeddert** [comment]
Fixed.
